backend:
  name: git-gateway
  branch: master
site_url: https://ricco.dev.br
display_url: https://ricco.dev.br
# logo_url: https://ricco.dev.br/assets/logo.png
locale: "pt"
publish_mode: editorial_workflow
media_folder: static/images
public_folder: images
collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    description: >
      All my blog posts
    folder: "src/pages/blog"
    slug: "{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    create: true
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true, default: "" }
      - { label: "Author", name: "author", widget: "string", required: true, default: "" }
      - { label: "Date", name: "published", widget: "date", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", required: true, default: "" }
      - { label: "Summary", name: "summary", widget: "string", required: true, default: "" }
      - { label: "Content", name: "body", widget: "markdown", hint: "Main content goes here." }
      - label: "Cover image"
        name: "cover_image"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false
      - label: "Categories"
        name: "categories"
        widget: "select"
        multiple: true
        options: ["feature", "configuration"]
      - { label: "Featured?", name: "featured", widget: "boolean", default: false, hint: "Should it be featured on the home page?" }
      - { name: "extends", widget: "hidden", required: true, default: "_layouts.post" }
      - { name: "layout", widget: "hidden", required: true, default: "blog" }